version: '3'
services:
  filebeat:
    hostname: filebeat
    image: bonita-logs-elastic-analyzer/filebeat:1.0.0
    build:
      context: filebeat
      dockerfile: Dockerfile
    volumes:
     - "${LOGS_DIR}:/var/log/bonita"
    links:
       - logstash
  kibana:
    image: kibana:6.8.7
    environment:
      - "LOGGING_QUIET=true"
    links:
      - elasticsearch
    ports:
      - 5601:5601
  logstash: 
    hostname: logstash 
    image: bonita-logs-elastic-analyzer/logstash:1.0.0
    build:
      context: logstash
      dockerfile: Dockerfile
    ports:
      - 5044:5044
    environment:
      LOG_LEVEL: error
    links:
      - elasticsearch
  elasticsearch:
    hostname: elasticsearch
    image: bonita-logs-elastic-analyzer/elasticsearch:1.0.0
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - cluster.name=bonita-logs-elastic-analyzer
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
